version: 0.2

phases:
  install:
    commands:
    - apt-get update
    - apt-get install -y unzip
    - wget https://releases.hashicorp.com/terraform/0.14.0/terraform_0.14.0_linux_amd64.zip
    - unzip terraform_0.14.0_linux_amd64.zip
    - mv terraform /usr/local/bin/
  pre_build:
    commands:
    - terraform init
  build:
    commands:
    - terraform plan -out=tfplan
  post_build:
    commands:
    - terraform apply -auto-approve tfplan
