version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
    # Install Terraform
    - wget https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_amd64.zip
    - unzip terraform_0.15.5_linux_amd64.zip
    - mv terraform /usr/local/bin/
  pre_build:
    commands:
    # (Optional) Initialize Terraform and set backend
    - terraform init
  post_build:
    commands:
    # (Optional) Perform any post-deployment tasks
    - echo "Deployment completed successfully"
