version: 0.2

phases:
  install:
    commands:
    - echo Installing dependencies...
  build:
    commands:
    - echo Build started on `date`
    - echo Compiling the application...
    - echo Build completed on `date`
  post_build:
    commands:
    - echo Build completed on `date`
artifacts:
  files:
  - '**/*'
