version: 0.2

phases:
  install:
    runtime-versions:
      terraform: 0.14 # Use a supported version of Terraform
  pre_build:
    commands:
    - pwd
    - terraform init
  build:
    commands:
    - terraform plan -out=tfplan
  post_build:
    commands:
    - terraform apply -auto-approve tfplan
