version: 0.2

phases:
  install:
    runtime-versions:
      terraform: 1.6 # Use the desired version of Terraform
  pre_build:
    commands:
    - terraform init
  build:
    commands:
    - terraform plan -out=tfplan
  post_build:
    commands:
    - terraform apply -auto-approve tfplan
